# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '2 2 2 * *'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build the image
        env:
          DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
        shell: pwsh
        run: ./build.ps1
